kind: Service
apiVersion: v1
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/address-pool: metallb-ip-range
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-img
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 3000
      restartPolicy: Always