apiVersion: v1

kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |+
    user                            www;
    worker_processes                auto; # it will be determinate automatically by the number of core
    
    error_log                       /var/log/nginx/error.log warn;
    pid                             /var/run/nginx/nginx.pid; # it permit you to use /etc/init.d/nginx reload|restart|stop|start
    
    events {
        worker_connections          1024;
    }
    
    http {
        include                     /etc/nginx/mime.types;
        default_type                application/octet-stream;
        sendfile                    on;
        access_log                  /var/log/nginx/access.log;
        keepalive_timeout           3000;
        
        server {
            listen 5050;
            listen [::]:5050;
            server_name _;
    
            root                    /var/www;
            index                   index index.php index.html index.htm;
            client_max_body_size    32m;
            error_page              500 502 503 504     /50x.html;
            location / {
                autoindex           on;
            }
            location ~ \.php$ {
                fastcgi_pass        127.0.0.1:9000;
                fastcgi_index       index.php;
                include             fastcgi.conf;
            }
            location = /50x.html {
                  root              /var/lib/nginx/html;
            }
            location ~ /\.ht {
                deny all;
          }
        }
    }


---
  
---

kind: Service
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/address-pool: metallb-ip-range
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress-img
        name: wordpress
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-config
            subPath: nginx.conf
            readOnly: true
        ports:
          - name: http
            containerPort: 5050
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config