kind: Service
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/address-pool: metallb-ip-range
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 5050
      restartPolicy: Always
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: wordpress-job
#   labels:
#     jobgroup: wordpress-job
# spec:
#   template:
#     metadata:
#       name: wordpress-job
#       labels:
#         jobgroup: wordpress-job
#     spec:
#       containers:
#       - name: wordpress
#         image: wordpress-img
#         command: ["sh", "-c", "echo Processing item && sleep 5"]
#       restartPolicy: Never
